on:
 push:
   branches: [ feat-pipeline-setup ]
  
 pull-request:
   branches:
    - [main]
defaults:
  run:
    working-directory: ./MathWorkshop

permissions:
 checks: write
 pull-requests: write

jobs:

 build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: Setup .NET
     uses: actions/setup-dotnet@v3
     with:
       dotnet-version: '8.0.x'
   - run: dotnet restore
     name: run dotnet restore

   - run: dotnet build
     name: run dotnet build

   - run: dotnet test --logger "trx;LogFileName=report.trx" --results-directory ./test-output
     name: tests
   - name: Publish test results
     uses: EnricoMi/publish-unit-test-result-action@v2
     if: always()
     with:
       files: ./MathWorkshop/test-output/*.trx